### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by jorisw** [st3fan/SadMacScreenSaver#4]
Hi, the screen saver contained in the .zip on your blog, yield this error message when trying to _enable_ it (even after authenticating for unknown software in the System Preferences > Security):

![image](https://user-images.githubusercontent.com/30017/80910814-763fdf00-8d32-11ea-8b58-c5e1b97a48be.png)

Building from source works, but then the screen saver only shows this when running:

![image](https://user-images.githubusercontent.com/30017/80910789-498bc780-8d32-11ea-99d3-cc4e98f6a69f.png)

macOS 10.15.4.

**Comment by st3fan** [comment]
Both these issues should be resolved with the latest release.
