### ISSUE TITLE
Locations are off with two screen setups

### ISSUE THREAD

**Issue by axello** [st3fan/SadMacScreenSaver#5]
3 bugs for the price of one!
* The sad macs only appear on the right side of my external screen. And then are cut of midway. The left part of external screen stays black; See attachment. 
[SadMac screenshots.zip](https://github.com/st3fan/SadMacScreenSaver/files/5122359/SadMac.screenshots.zip)

Super weird:
* Internal screen shows only static Mac in the middle until, after a while, the randomly filled screen appears at once. Sometimes after 20 seconds, but I also had to wait 90 seconds for the internal screen to appear.

* I dearly miss an icon in the screen savers section, but I guess Apple won't approve with your default choice.
<img width="780" alt="icon missing" src="https://user-images.githubusercontent.com/149241/91151701-4db36a80-e6be-11ea-81e4-c111956066d2.png">

* it runs fine under Cataline

**Comment by st3fan** [comment]
I think I fixed all these issues with the 1.3 release. Although I am not 100% sure about the second bug.
